### ISSUE TITLE
fails if no credentials file

### ISSUE THREAD

**Issue by jhaynie** [rivethealth/aws-saml-cli#7]
i no aws credentials file:

```Traceback (most recent call last):
  File "/usr/local/bin/aws-saml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awscli_saml/main.py", line 39, in main
    saml=args.saml,
  File "/usr/local/lib/python3.7/site-packages/awscli_saml/assume_role.py", line 28, in run
    section_name, "saml.session_duration"
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'profile pinpt'```

**Comment by pauldraper** [comment]
This error happens if you lack a config file and don't provide the necessary session duration, IDP ARN, and role ARN as CLI parameters.

Session duration ought to be optional, so I'll keep the issue open to fix that.

**Comment by zaro0508** [comment]
I believe PR #14 made the session duration optional.
